# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "my_dev"

  config.vm.synced_folder "../", "/my_dev_packer_script"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    
    vb.customize [
      "modifyvm", :id,
      "--clipboard", "bidirectional",
      "--memory", "1024",
      "--vram", "64",
      "--accelerate3d", "off",
      "--accelerate2dvideo", "off",
      "--hwvirtex", "on",
      "--nestedpaging", "on",
      "--largepages", "on",
      "--ioapic", "on",
      "--pae", "on",
    ]
    
  end

end
